const statusText = document.getElementById('status-text');
const subText = document.getElementById('sub-text');
const timestampText = document.getElementById('timestamp');

async function checkStatus() {
    try {
        // Fetch the static JSON file generated by GitHub Actions
        // The query string prevents the browser from loading a cached version
        const response = await fetch('./status.json?v=' + new Date().getTime());
        const data = await response.json();
        
        statusText.innerText = data.status;
        
        if (data.status === 'OPEN') {
            document.body.style.backgroundColor = '#28a745'; // Green
            document.body.style.color = 'white';
            subText.innerText = `Confirmed via local chatter. (Open Score: ${data.confidence.openScore})`;
        } else if (data.status === 'CLOSED') {
            document.body.style.backgroundColor = '#dc3545'; // Red
            document.body.style.color = 'white';
            subText.innerText = `Still closed for remodel. (Closed Score: ${data.confidence.closedScore})`;
        } else if (data.status === 'OPENING SOON') {
            document.body.style.backgroundColor = '#ffc107'; // Yellow
            document.body.style.color = '#333'; 
            subText.innerText = `Mixed signals detected. Keep an eye out.`;
        } else {
            document.body.style.backgroundColor = '#6c757d'; // Gray
            document.body.style.color = 'white';
            subText.innerText = `Not enough recent data to determine status.`;
        }

        if (data.lastChecked) {
            const date = new Date(data.lastChecked);
            timestampText.innerText = `Last checked by GitHub Actions: ${date.toLocaleTimeString()} on ${date.toLocaleDateString()}`;
        }
        
    } catch (error) {
        statusText.innerText = 'ERROR';
        document.body.style.backgroundColor = '#343a40'; 
        subText.innerText = 'Could not load status data. The GitHub Action may not have run yet.';
    }
}

// Run immediately on page load
checkStatus();

// Refresh the frontend every 5 minutes in case the user leaves the tab open
setInterval(checkStatus, 300000);
